#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json
test_format = 1.0

[default]

    preinstall = """
        sudo yunohost tools update apps
        sudo yunohost app install --force https://github.com/YunoHost-Apps/synapse_ynh/ \
            -a "domain=$domain&server_name=$server_name&is_free_registration=$is_free_registration&jitsi_server=$jitsi_server"
    """

    args.botadmin = "@johndoe:synapsedomain.tld"
    args.botusers = "synapsedomain.tld"

    test_upgrade_from.e45a5c8d2d9f4a1e6a879aa518f8464822793be6.name = "0.4.3~ynh1"
